### ISSUE TITLE
Service name normalization inconsistency

### ISSUE THREAD

**Issue by tunerex** [TuneOSS/freight_forwarder#17]
I have problem deploying services with names including `-` character.

``` yml
..
# service
classic-web:
  image: ....
...
environment:
  staging:
    hosts:
      default: 
        - *localhost
      classic-web: *staging-hosts
...  
```

I poked a code a bit, I think it is some sort of inconsistency regarding `key` normalization throughout config object and service alias

Printing some debug message just before the line:
https://github.com/TuneOSS/freight_forwarder/blob/e7476c67a22241fc1ad24826d132ddb2a2a412c1/freight_forwarder/freight_forwarder.py#L374-L377

``` python
fleet = commercial_invoice.container_ships.get(
  host_alias,
  commercial_invoice.container_ships.get('default')
)
```

I got:

``` bash
host_alias is equal to:
classic-web

commercial_invoice is equal to:
{'classic_web': {'https://some.random.url:2376': <freight_forwarder.container_ship.ContainerShip object at 0x104041250>, 'https://p-audiences01-sta.use01.plat.priv:2376': <freight_forwarder.container_ship.ContainerShip object at 0x104041610>}, 'default': {'https://192.168.99.100:2376': <freight_forwarder.container_ship.ContainerShip object at 0x104041a50>}}
```

Judging from the line here:
https://github.com/TuneOSS/freight_forwarder/blob/e7476c67a22241fc1ad24826d132ddb2a2a412c1/freight_forwarder/config.py#L904-L905

``` python
 if '-' in attr_name:
            attr_name = attr_name.replace('-', '_')
```

dash lines are being normalized into underscore. Somehow, host_alias stored within `commercial_invoice.transport_service.name` isn't normalized in same manner.

From there, I didn't poke deeper, hoping for some guidance how to resolve this issue.

Help? xD

**Comment by abanna** [comment]
I can take a look at this this evening.

**Comment by tunerex** [comment]
@abanna, 
I got a message from @fin09pcap that the issue might have been already resolved by fixing other set of bugs. 
I am waiting on his confirmation.
